/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vCloudBackup;

import javax.swing.JOptionPane;

import util.Settings;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import java.awt.Window.Type;

/**
 *
 * @author Administrator
 */
public class LoginDialog extends javax.swing.JDialog 
{
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordBox;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField usernameBox;
    private javax.swing.JLabel usernameLabel;
    private JComboBox<Settings.VCloudServer> vCloudComboBox;
    
    private boolean cancelled;
    private Settings settings;
    private String username;
    private String password;
    private Settings.VCloudServer vCloudServer;
    private boolean showServerDropDown = true;
    
    public String getUsername()
    {
        return this.username;
    }
    
    public String getPassword()
    {        
        return this.password;
    }
    
    public Settings.VCloudServer getVCloudServer()
    {        
        return this.vCloudServer;
    }
    
    public boolean getCancelled()
    {
        return this.cancelled;
    }
    
    public void setShowServerDropDown(boolean showServerDropDown)
    {
    	this.showServerDropDown = showServerDropDown;
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * Creates new form LoginDialog
     * @wbp.parser.constructor
     */
    private LoginDialog(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        setUndecorated(true);
        setType(Type.UTILITY);
        setModal(true);
        initComponents(true);       
    }
    

	public LoginDialog(java.awt.Frame parent, boolean modal, Settings settings) 
    {
        super(parent, modal);
        setUndecorated(true);
        setType(Type.UTILITY);
        setModal(true);
        initComponents(true);
        
        this.settings = settings;

        SetupVCenterBox();
    }
    
    
    public LoginDialog(java.awt.Frame parent, boolean modal, Settings settings, boolean showServers) 
    {
        super(parent, modal);
        initComponents(showServers);
        
        this.settings = settings;
        this.usernameBox.setText(username);
        this.passwordBox.setText(password);
        

        SetupVCenterBox();
    }
    
    
    public LoginDialog(java.awt.Frame parent, boolean modal, Settings settings, String username, String password) 
    {
        super(parent, modal);
        initComponents(true);
        
        this.settings = settings;
        this.usernameBox.setText(username);
        this.passwordBox.setText(password);
        

        SetupVCenterBox();
    }
    
    
    public LoginDialog(java.awt.Frame parent, boolean modal, Settings settings, String username, String password, boolean showServers) 
    {
        super(parent, modal);
        initComponents(showServers);
        
        this.settings = settings;
        this.usernameBox.setText(username);
        this.passwordBox.setText(password);
        

        SetupVCenterBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents(boolean showServers) 
    {
        usernameLabel = new javax.swing.JLabel();
        usernameBox = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordBox = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login to vCLoud");
        setAlwaysOnTop(true);

        usernameLabel.setLabelFor(usernameBox);
        usernameLabel.setText("Username:");

        usernameBox.setToolTipText("Username used to access vCloud Director");

        passwordLabel.setLabelFor(passwordBox);
        passwordLabel.setText("Password:");
        passwordLabel.setToolTipText("");

        passwordBox.setToolTipText("Password used to access vCloud Director");

        loginButton.setText("Login");
        loginButton.setToolTipText("Login to vCloud");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.setToolTipText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        
        vCloudComboBox = new JComboBox();
        vCloudComboBox.setVisible(showServers);
        
        JLabel lblVcenter = new JLabel("vCenter:");
        lblVcenter.setVisible(showServers);
	
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(cancelButton)
        					.addPreferredGap(ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
        					.addComponent(loginButton))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(passwordLabel)
        						.addComponent(usernameLabel)
        						.addComponent(lblVcenter))
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(passwordBox)
        						.addComponent(usernameBox, 235, 235, Short.MAX_VALUE)
        						.addComponent(vCloudComboBox, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(usernameBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(usernameLabel))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(passwordBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(passwordLabel))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(vCloudComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblVcenter))
        			.addPreferredGap(ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(loginButton)
        				.addComponent(cancelButton))
        			.addContainerGap())
        );
        
        
        
        getContentPane().setLayout(layout);

        pack();
    }

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) 
    {
        String errorTitle = "Invalid Credentials";
        String errorMassage = "Sorry, you must enter a username and password!";
        
        
        if ("".equals(this.usernameBox.getText()) || this.passwordBox.getPassword() == null)
        {
            JOptionPane.showMessageDialog(this, errorMassage, errorTitle, JOptionPane.ERROR_MESSAGE);
        }
        
        else
        {
        	this.username = usernameBox.getText();
        	this.password = new String(this.passwordBox.getPassword());
        	this.vCloudServer = (Settings.VCloudServer)vCloudComboBox.getSelectedItem();
        	
            this.setVisible(false);
        }
    }
    
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) 
    {
        this.cancelled = true;
        
        this.setVisible(false);
    }
    

    private void SetupVCenterBox()
	{
    	for (Settings.VCloudServer vCloudServer : settings.getvCloudServers())
    		this.vCloudComboBox.addItem(vCloudServer);
    	
    	
        vCloudComboBox.setSelectedIndex(0);
	}
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginDialog dialog = new LoginDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
}
